const ar = {
    dashboard: "لوحة القيادة",
    layoutBuilder: "Layout builder",
    craft: "Crafted",
    pages: "Pages",
    profile: "Profile",
    profileOverview: "Overview",
    projects: "Projects",
    campaigns: "Campaigns",
    documents: "Documents",
    connections: "Connections",
    wizards: "Wizards",
    horizontal: "Horizontal",
    vertical: "Vertical",
    account: "Account",
    accountOverview: "Overview",
    settings: "إعدادات",
    authentication: "المصادقة",
    basicFlow: "Basic Flow",
    signIn: "تسجيل الدخول",
    signUp: "اشتراك",
    passwordReset: "إعادة تعيين كلمة المرور",
    multiStepSignUp: "Multi-steps Sign up",
    error404: "خطأ 404",
    error500: "خطأ 500",
    apps: "تطبيقات",
    chat: "Chat",
    privateChat: "Private Chat",
    groupChat: "Group Chat",
    drawerChat: "Drawer Chat",
    widgets: "Widgets",
    widgetsLists: "Lists",
    widgetsStatistics: "Statistics",
    widgetsCharts: "الرسوم البيانية",
    widgetsMixed: "Mixed",
    widgetsTables: "الجداول",
    widgetsFeeds: "Feeds",
    changelog: "Changelog",
    docsAndComponents: "Docs & Components",
    megaMenu: "Mega Menu",
    exampleLink: "Example link",
    modals: "مشروط",
    general: "عام",
    inviteFriends: "ادعو أصدقاء",
    viewUsers: "عرض المستخدمين",
    upgradePlan: "Upgrade Plan",
    shareAndEarn: "Share & Earn",
    forms: "نماذج",
    newTarget: "New Target",
    newCard: "New Card",
    newAddress: "New Address",
    createAPIKey: "Create API Key",
    twoFactorAuth: "Two Factor Auth",
    createApp: "Create App",
    createAccount: "Create Account",
    documentation: "Documentation",
    components: "Components",
    resources: "Resources",
    activity: "نشاط",
    customers: "عملاء",
    gettingStarted: "Getting Started",
    customersListing: "Customers Listing",
    customerDetails: "Customers Details",
    calendarApp: "تقويم",
    subscriptions: "Subscriptions",
    getStarted: "Getting Started",
    subscriptionList: "Subscription List",
    addSubscription: "Add Subscription",
    viewSubscription: "View Subscription",
    Generalpercentagesem :"النسب العامة الخاصة بالطوارئ",
    Generalpercentageshr:"النسب العامة للموارد البشرية",
    addcontractor:'اضافة متعهد',
    listofunits:'قائمة الوحدات',
    addunitypes:'اضافة انواع الوحدات',
    newunit:'تسجيل وحدة جديدة',
    listofusers:'قائمة المستخدمين',
    adduscores:'اضافة مهام المستخدمين',
    category:'طبيعة الاعمال',
    addnewuser:'اضافة مستخدم جديد',
    Reports:'التقارير',
    performanceem:'تقرير اداء موظفى الطوارئ',
    performancehr:"تقرير اداء موظفى الموارد البشرية",
    humanresource:"تقرير الموارد البشرية",
    emergency_report:"تقرير الطوارئ",
    notcompletedtaskem:"مهام الطوارئ المرفوضة",
    notcompletedtaskhr:"مهام الموارد البشرية المرفوضة",
    pendingtaskem:"مهام الطوارئ المعلقة",
    pendingtaskhr:"مهام الموارد البشرية المعلقة",
    completedtaskem: "مهام الطوارئ المكتملة",
    completedtaskhr:"مهام الموارد البشرية المكتملة",
    surveylistforreport:"تقارير النماذج",
    units_status_em:"تقرير نسب انجاز للطوارئ",
    units_status_hr: "تقرير نسب انجاز للموارد البشرية",
    Applications:"التطبيقات",
    todolist:"قائمة المهام",
    surveylist:"إنشاء تقييم",
    survey:"إنشاء النماذج",
    generalratios:'النسب العامة الخاصة بالموارد البشرية',
    contractorlist:'قائمة المتعهدين :-',
    listunits:'قائمة الوحدات :',
    listunittypes:'قائمة انواع الوحدات :-',
    unitregistrationform:'نموذج تسجيل الوحدات',
    userpermission:'صلاحيات المستخدمين',
    gradelist:'قائمة مهام المستخدمين:-',
    categorylist:'قائمة مجموعة المستخدمين',
    userregistrations:'تسجيل المستخدمين :',
    reportstaffem:'تقرير اداء موظفي الطوارئ :',
    reportstaffhr:'تقرير اداء موظفي الموارد البشرية :',
    hrreport:'تقرير الموارد البشرية',
    emreport:'تقرير الطوارئ',
    rejectassign:'مهمة مرفوضة',
    pendingtask:'المهام المعلقة',
    completedtask:'المهام المكتملة',
    passingpercentage:'نسب الاجتياز :-',
    surveyt:'تقييم',
    home:'بيت',
    default_em:'الافتراضي م',
    default:'الإفتراضي',
    contractor:'مقاول',
    unitsupdate:'تحديث الوحدات',
    Unitestypes:'أنواع الوحدات',
    Units:'الوحدات',
    usersupdate:'تحديث المستخدمين',
    roles:'الأدوار',
    natureb:'فئة',
    register:'يسجل',
    performance_em:'أداء الطوارئ',
    performance_hr:'أداء الموارد البشرية',
    human_resource:'الموارد البشرية',
    EditList:'تحرير القائمة',
    totalrating:'اجمالى التقيمات',
    emergencytask:'المهام الخاصة بالطوارئ',
     hrtasks:'المهام الخاصة بالموارد البشرية',
    holystage:'مرحلة المشاعر المقدسة', 
    noofflight:'عدد الرحلات المنجزة',
    noofpilgrims:'عدد الحجاج',
    totallabor:'اجمالى العمالة الموفرة',
    averagetime:'متوسط الوقت المستغرق للانجاز',
    averageno:'متوسط عدد العمالة للرحلة',
    departurestage:'مرحلة المغادرة',
    newcontractor:'اضافة متعهد جديد',
    serialno:'الرقم المسلسل',
    contractorname:'إسم المتعهد',
    buildingno:'رقم المبنى',
    customername:'اسم العميل',
    unitno:'رقم الوحدة',
    typeunit:'نوع الوحدة',
    events:'الاحداث',
    details:'تفاصيل',
    placecontractor:'من فضلك ادخل اسم المتعهد هنا',
    cancel:'الغاء',
    save:'حفظ',
    pleasewait:'انتظر من فضلك...',
    reqcon:'مطلوب اسم المقاول',
    addunittype:'اضافة نوع وحدة جديد',
    placeunittype:'من فضلك ادخل نوع الوحدة هنا',
    requnittype:'نوع الوحدة مطلوب',
    reqcat:'الفئة مطلوبة',
    addnewunit:'اضافة وحدة جديدة',
    deparmentname:'اسم القسم',
    reqscore:'النتيجة مطلوبة',
    userscore:'درجة المستخدم',
    placescore:'من فضلك ادخل درجة المستهدم هنا',
    addnewscore:'اضافة مهام مستخدم جديد',
    addnewsurvey:'اضافة نموذج جديدة',
    title:'عنوان',
    cat:'فئة',
    detail:'تفاصيل',
    reqtitle:'العنوان مطلوب',
    detailreq:"التفاصيل مطلوبة",
    selectcategory:"الرجاء تحديد الفئة",
    selectmaster:"الرجاء تحديد رئيسي",
    savedsuccess:'تم الحفظ بنجاح',
    hajj:'الوحدات التنفيذية للحج خدمات الحج رقم',
    nationality:'الجنسية',
    buidling_owner:'اسم صاحب العمارة',
    permitno:'رقم التصريح',
    selectcontractor:'اختر المتعهد',
    typeunits:'انواع الوحدات',
    uploadfile:'رفع ملف',
    firstname:'الاسم الاول',
    lastname:'الاسم الاخير',
    mobile:'رقم الجوال',
    e_mail:'البريد الالكتروني', 
    function:'الوظيفة',
    validity:'الصلاحية',
    powers:'الصلاحيات',
    additions:'اضافة',
    delete:'حذف',
    unitname:'اسم الوحدة',
    process:'العمليات',
    areyousure:'هل انت متاكد ؟',
    notretrivedata:'لن تستطيع استرجاع البينات مرة اخرى !',
    deletesuccess:'تم الحذف بنجاح',
    cancelerror:'"الغاء", "لم يتم حذف البيانات ", "خطا"',
    phone:'رقم الهاتف',
    password:'كلمة السر',
    selectdegree:'اختر الدرجة',
    choosecategory:'اختر الفئة',
    registration:'تسجيل',
    discard:'إلغاء',
    export:'تصدير',
    rejectemtask:'المهام المرفوضة الخاصة بالطوارى :',
    rejecthrtask:'المهام المرفوضة الخاصة بالموارد البشرية:',
    signout:'تسجيل الخروج',
    signin:'تسجيل الدخول',
    continue:'يكمل',
    successloggedin:'لقد قمت بتسجيل الدخول بنجاح!',
    okgotit:'حسنًا ، حسنًا!',
    tryagain:'حاول ثانية!',
    thedate:'التاريخ',
    thedetails:'التفاصيل',
    themission:'المهمة',
    thecondition:'الحالة',
    unitadministrator:'مسوول الوحدة',
    pendingemtask:'المهام المعلقة الخاصة بالطوارى :',
    pendinghrtask:'المهام المعلقة الخاصة بالموارد البشرية:',
    completedemtask:'المهام المكتملة الخاصة بالطوارى :',
    completedhrtask:'المهام المكتملة الخاصة بالموارد البشرية:',
    theuser:'المستخدم',
    buildingn:'رقم العمارة',
    executiveunit:'الوحدة التنفيذية',
    theevent:"الحدث",
    printing:'الطباعة',
    amendment:'التعديل',
    print:'طباعة',
    unit:'الوحدة',
    thequestion:'السؤال',
    theanswers:'الاجابات',
    attachments:'المرفقات',
    comments:'ملاحظات',
    taskimage:'صورة المهمة',
    tasknotes:'ملاحظات المهمة',
    taskstatus:'حالة المهمة ',
    usertask:'مهمة المستخدم',
    sample:'النموذج',
    formdetails:'تفاصيل النموذج',
    successrate:'نسبة النجاح',
    mistakepercentage:'نسبة الخطا',
    searchbymodelname:'البحث ب اسم النموذج',
    searchbyunitno:'البحث برقم الوحدة',
    searchbyinsname:'البحث باسم المفتش',
    search:'بحث',
    question:'سؤال',
    status:'حالة',
    date:'تاريخ', 
    missiondetails:'تفاصيل المهمة',
    taskname:'اسم المهمة',
    attachfile:'إرفاق ملف ',
    tobesure:'تاكيد',
    completed:'مكتملة',
    suspended:'معلقة',
    notdone:'لم تتم',
    chooseunit:'اختر الوحدة',
    employeename:'اسم الموظف',
    undertaker:'المتعهد',
    assignto:'إسناد إلى',
    addnew:'اضف جديد',
    summary:'ملخص',
    edit:'يحرر',
    addquestions:'أضف أسئلة',
    text:'نص',
    choosemultiple:'اختار من متعدد',
    multiplechoice:'اختيار متعدد',
    answertype:'نوع الإجابة',
    addanswer:'اضافة اجابة',
    changepassword:'تغيير كلمة السر',
    light:'ضوء',
    dark:'مظلم',
    system:'نظام',
    quicklink:'روابط سريعة',
    generalproportion:'النسب العامة طواري',
    generalpresources:'النسب العامة موارد',
    achievementratios:'نسب انجاز طواري',
    generalcompletion:'نسب انجاز موارد',
    accomplishmentcontractor:' انجاز المتعهدين',
    notifications:'الإخطارات',
    viewall:'مشاهدة الكل',
    About:'بشأن',
    Support:'يدعم',
    Purchase:'الشراء',
    permission:'إذن',
    passwordsave:'تم تغيير كلمة السر  بنجاح',
    newpass:' كلمة السر الجديدة',
    emailreq:'إن البريد الإلكترونى حقل مطلوب',
    passreq:'كلمة المرور هي حقل مطلوب',
    minpass:'يجب أن تتكون كلمة المرور من 4 أحرف على الأقل',
    terms:"مصطلحات",
    plans:'الخطط',
    contactus:'اتصل بنا',
    firstnamereq:'الاسم الأول هو حقل مطلوب',
    lastnamereq:'اسم العائلة هو حقل مطلوب',
    nationalityreq:'الجنسية هي حقل مطلوب',
    mobilereq:'المحمول هو حقل مطلوب',
    rolereq:'الدور هو حقل مطلوب',
    catreq:'الفئة هي حقل مطلوب',
    newpassreq:'كلمة المرور الجديدة هي حقل مطلوب',
    yesdelete:'نعم ، احذف!',
    nocancel:'لا ، الغاء!',
    unitreq:'يعد unit_number حقلاً مطلوبًا',
    pilgrimsreq:'الجنسية هي حقل مطلوب',
    buildingreq:'Building_number هو حقل مطلوب',
    representreq:'إضافة مكاتب مسجلة',
    clientreq:'client_id هو حقل مطلوب',
    permissionreq:'الأذونات حقل مطلوب',
    companyreq:'الشركة حقل مطلوب',
    typereq:'النوع هو حقل مطلوب',
    percentagecontractor:'نسب انجاز المتعهدين',
    Contractor_ratios:'نسب المقاول',
    masters:'قائمة الاعدادات',
    industrytype:'الاعمال الموسمية',
    inspectiontype:'الإدارات',
    inspectionpropertytype:'النماذج المستخدمة',
    registeredproperty:'المكاتب المسجلة',
    addnewtype:'أضف نوع صناعة جديد',
    name:'اسم',
    arabic:'عربي',
    english:'إنجليزي',
    name_ar_req:'الاسم مطلوب باللغة العربية',
    name_en_req:'الاسم مطلوب باللغة الإنجليزية',
    addinspectiontype:'أضف نوع فحص جديد',
    selectowner:'حدد مالك العقار',
    selectindustrytype:'حدد نوع الصناعة',
    ownerreq:'الرجاء تحديد المالك',
    industryreq:'الرجاء تحديد نوع الصناعة',
    ownerreq_en:'مطلوب اسم المالك باللغة الإنجليزية',
    ownerreq_ar:'مطلوب اسم المالك باللغة العربية',
    owner:'مالك',
    selectproperty:'حدد خاصية الاستقصاء',
    list:'١ (رقم المركز)',
    noofpeople:'٢(عدد الحجاج )',
    inspectionreq:'الرجاء تحديد نوع العقار',
    noofpreq:'الحقل مطلوب',
    active:'نشيط',
    archive:'أرشيف',
    action:'الإجراء',
    selectinspectiontype:'حدد نوع التفتيش',
    selectinspectionproperty:'حدد نوع خاصية الفحص',
    selectregisteredproperty:'حدد الملكية المسجلة',
    editsurvey:'تحديث الاستبيان',
    editcontractor:'تحديث المقاول',
    passwordless:'يجب ألا تقل كلمة المرور الجديدة عن 6 أحرف',
    propertytype:'نوع المنشأة',
    editpropertytype:'تحرير نوع الخاصية',
    addpropertytype:'إضافة نوع الخاصية',
    addregisteredproperty:'أضف خاصية مسجلة',
    selectpropertytype:'حدد خاصية',
    passless:'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل',
    emailmobile:'البريد الإلكتروني / الهاتف مطلوب',
    emailphoneinvalid:'البريد الإلكتروني / الهاتف غير صالح',
    addfields:'أضف الحقول',
    pleasetry:'كلمة المرور غير تحديث! يرجى المحاولة بعد مرور بعض الوقت',
    yesarchive:'نعم أرشفة',
    representative:'ممثل',
    reqselectproperty:'الرجاء تحديد خاصية',
    permitnoreq:'رقم التصريح هو حقل مطلوب',
    owner_req:'المالك هو حقل مطلوب',
    offices:'مكاتب',
    buildingname:'إسم المبنى',
    buildingnamereq:'اسم المبنى هو حقل مطلوب',
    licenseno:'رقم الرخصة',
    newpassword:'كلمة المرور الجديدة',
    enterpassword:'الرجاء إدخال كلمة مرور جديدة',
    registeredproperties:'الخصائص المسجلة',
    addrolegroup:'إضافة مجموعة دور المستخدم',
    addinspectionpropertytype:'أضف نوع خاصية استقصاء جديد',
    addusergroup:'أضف مجموعة مستخدمين ',
    adduserrole:'إضافة دور مستخدم جديد',
    
  }

  export default ar;