const en = {
    dashboard: "Dashboard",
    layoutBuilder: "Layout builder",
    craft: "Crafted",
    pages: "Pages",
    profile: "Profile",
    profileOverview: "Overview",
    projects: "Projects",
    campaigns: "Campaigns",
    documents: "Documents",
    connections: "Connections",
    wizards: "Wizards",
    horizontal: "Horizontal",
    vertical: "Vertical",
    account: "Account",
    accountOverview: "Overview",
    settings: "Settings",
    authentication: "Authentication",
    basicFlow: "Basic Flow",
    signIn: "Sign-in",
    signUp: "Sign-up",
    passwordReset: "Password Reset",
    multiStepSignUp: "Multi-steps Sign up",
    error404: "Error 404",
    error500: "Error 500",
    apps: "Apps",
    chat: "Chat",
    privateChat: "Private Chat",
    groupChat: "Group Chat",
    drawerChat: "Drawer Chat",
    widgets: "Widgets",
    widgetsLists: "Lists",
    widgetsStatistics: "Statistics",
    widgetsCharts: "Charts",
    widgetsMixed: "Mixed",
    widgetsTables: "Tables",
    widgetsFeeds: "Feeds",
    changelog: "Changelog",
    docsAndComponents: "Docs & Components",
    megaMenu: "Mega Menu",
    exampleLink: "Example link",
    modals: "Modals",
    general: "General",
    inviteFriends: "Invite Friends",
    viewUsers: "View Users",
    upgradePlan: "Upgrade Plan",
    shareAndEarn: "Share & Earn",
    forms: "Forms",
    newTarget: "New Target",
    newCard: "New Card",
    newAddress: "New Address",
    createAPIKey: "Create API Key",
    twoFactorAuth: "Two Factor Auth",
    createApp: "Create App",
    createAccount: "Create Account",
    documentation: "Documentation",
    components: "Components",
    resources: "Resources",
    activity: "Activity",
    customers: "Customers",
    gettingStarted: "Getting Started",
    customersListing: "Customers Listing",
    customerDetails: "Customers Details",
    calendarApp: "Calendar",
    subscriptions: "Subscriptions",
    getStarted: "Getting Started",
    subscriptionList: "Subscription List",
    addSubscription: "Add Subscription",
    viewSubscription: "View Subscription",
    Generalpercentagesem:"General percentages for emergencies",
    Generalpercentageshr:"General ratios of human resources",
    addcontractor:'Add Contractor',
    listofunits:'Module list',
    addunitypes:'Adding Unit Types',
    newunit:'Register a new unit',
    listofusers:'User list',
    //adduscores:'Add Users',
    adduscores:'Users Roles',
    // category:'Nature of Business',
    category:'User Role Group',
    addnewuser:'Add a new user',
    Reports:'Reports',
    performanceem:'Emergency staff performance report',
    performancehr:"HR employee performance report",
    humanresource:"HR report",
    emergency_report:"Emergency Report",
    notcompletedtaskem:"Denied emergency missions",
    notcompletedtaskhr:"Rejected HR tasks",
    pendingtaskem:"Outstanding emergency missions",
    pendingtaskhr:"Outstanding HR tasks",
    completedtaskem: "Completed emergency tasks",
    completedtaskhr:"Completed HR tasks",
    surveylistforreport:"Template reports",
    units_status_em:"Emergency completion rate report",
    units_status_hr: "Report of achievement percentages for human resources",
    Applications:"Applications",
    todolist:"Todo list",
    surveylist:"Create an assessment",
    survey:"Create forms",
    generalratios:'General ratios of human resources',
    contractorlist:'List of contractors:',
    listunits:'List of units:',
    listunittypes:'List of unit types:',
    unitregistrationform:'Unit registration form',
    userpermission:'User Permissions',
    gradelist:'User Role list:',
    categorylist:'List of Users Group',
    userregistrations:'Register New User:',
    reportstaffem:'Emergency staff performance report:',
    reportstaffhr:'HR staff performance report:',
    hrreport:'HR report',
    emreport:'Emergency Report',
    rejectassign:'Rejected assignment',
    pendingtask:'Pending Tasks',
    completedtask:'Completed Tasks',
    passingpercentage:'Passing Percentages:',
    surveyt:'Evaluation',
    home:'Home',
    default_em:'Em default',
    default:'Default',
    contractor :'Contractor',
    unitsupdate:'Update units',
    Unitestypes:'Unit types',
    Units:'Units',
    usersupdate:'Update Users', 
    roles:'Roles',
    natureb:'Category',
    register:'Register',
    performance_em:'performance_em',
    performance_hr:'performance_hr',
    human_resource:'human_resource',
    EditList:'Edit List',
    totalrating:'Total Ratings',
    emergencytask:'Emergency Tasks',
    hrtasks:'Human resources tasks',
    holystage:'Holy feelings stage',
    noofflight:'The number of flights completed',
    noofpilgrims:'The number of pilgrims',
    totallabor:'Total labor saved',
    averagetime:'Average time to complete',
    averageno:'The average number of workers for the trip',
    departurestage:'Departure Stage',
    newcontractor:'Add a new contractor',
    serialno:'Serial Number',
    contractorname:"Contractor's Name",
    buildingno:'Building Number',
    customername:'Customer Name',
    unitno:'Unit Number',
    typeunit:'Unit Type',
    events:'Events',
    details:'Details',
    placecontractor:"Please enter the contractor's name here",
    cancel:'Cancellation',
    save:'Save',
    pleasewait:'Please wait...',
    reqcon:"Contractor's name is required",
    addunittype:'Add a new unit type',
    placeunittype:'Please enter the unit type here',
    requnittype:'Unit type is required',
    reqcat:'Category is required',
    addnewunit:'Add a new unit',
    deparmentname:'Department Name',
    reqscore:'Score is required',
    userscore:'User Score',
    placescore:'Please enter user score here',
    addnewscore:'Add a new user',
    addnewsurvey:'Add New Form',
    title:'Title',
    cat:'Category',
    detail:'Detail',
    reqtitle:'Title is required',
    detailreq:"Detail is required",
    selectcategory:"Please select category",
    selectmaster:"Please select master",
    savedsuccess:'Saved successfully',
    hajj:'Hajj Executive Units Hajj Services No',
    nationality:'Nationality',
    buidling_owner:'The name of the owner of the building',
    permitno:'Permit Number',
    selectcontractor:'Choose the contractor',
    typeunits:'Types of units',
    uploadfile:'Upload file',
    firstname:'First Name',
    lastname:'Last Name',
    mobile:'Mobile Number',
    e_mail:'E-mail',
    function:'Function',
    validity:'Validity',
    powers:'Powers',
    additions:'Addition',
    delete:'Delete',
    unitname:'Unit name',
    process:'Processes',
    areyousure:'Are You Sure ?',
    notretrivedata:'You will not be able to retrieve data again!',
    deletesuccess:'Deleted successfully',
    cancelerror:'"Cancel", "Data not deleted", "Error"',
    phone:'Phone Number',
    password:'Password',
    selectdegree:'Choose the degree',
    choosecategory:'Choose Category',
    registration:'Registration',
    discard:'Discard',
    export:'Export',
    rejectemtask:'Rejected emergency tasks:',
    rejecthrtask:'Rejected tasks related to human resources:',
    signout:'Sign Out',
    signin:'Sign In',
    continue:'Continue',
    successloggedin:'You have successfully logged in!',
    okgotit:'Ok, got it!',
    tryagain:'Try again!',
    thedate:'The Date',
    thedetails:'The Details',
    themission:'The Mission',
    thecondition:'The Condition',
    unitadministrator:'Unit Administrator',
    pendingemtask:'Emergency pending tasks:',
    pendinghrtask:'HR pending tasks:',
    completedemtask:'Emergency completed tasks:',
    completedhrtask:'HR tasks completed:',
    theuser:'The User',
    buildingn:'Building Number',
    executiveunit:'Executive unit',
    theevent:'The Event',
    printing:'Printing',
    amendment:'Amendment',
    print:'Print',
    unit:'Unit',
    thequestion:'The Question',
    theanswers:'The Answers',
    attachments:'Attachments',
    comments:'Comments',
    taskimage:'Task Image',
    tasknotes:'Task Notes',
    taskstatus:'Task Status',
    usertask:'User Task',
    sample:'Sample',
    formdetails:'Form details',
    successrate:'The success rate',
    mistakepercentage:'Mistake Percentage',
    searchbymodelname:'Search by model name',
    searchbyunitno:'Search by unit number',
    searchbyinsname:'Search by inspector name',
    search:'Search',
    question:'Question',
    status:'Status',
    date:'Date',
    missiondetails:'Mission details',
    taskname:'Task Name',
    attachfile:'Attach a file',
    tobesure:'to be sure',
    completed:'Completed',
    suspended:'Suspended',
    notdone:'Not Done',
    chooseunit:'Choose the unit',
    employeename:'Employee Name',
    undertaker:'Undertaker',
    assignto:'Assign To',
    addnew:'Add New',
    summary:'Summary',
    edit:'Edit',
    addquestions:'Add Questions',
    text:'Text',
    choosemultiple:'Choose from multiple',
    multiplechoice:'Multiple choice',
    answertype:'Answer type',
    addanswer:'Add an answer',
    changepassword:'Change Password',
    light:'Light',
    dark:'Dark',
    system:'System',
    quicklink:'Quick Links',
    generalproportion:'General proportions are contingent',
    generalpresources:'General proportions resources',
    achievementratios:'Achievement ratios',
    generalcompletion:'Resource completion percentages',
    accomplishmentcontractor:'Accomplishment of contractors',
    notifications:'Notifications',
    viewall:'View All',
    About:'About',
    Support:'Support',
    Purchase:'Purchase',
    permission:'permission',
    passwordsave:'Password changed successfully',
    newpass:'New Password',
    emailreq:'Email is a required field',
    passreq:'Password is a required field',
    minpass:'Password must be at least 4 characters',
    terms:"Terms",
    plans:'Plans',
    contactus:'Contact Us',
    firstnamereq:'Firstname is a required field',
    lastnamereq:'Lastname is a required field',
    nationalityreq:'Nationality is a required field',
    mobilereq:'Mobile is a required field',
    rolereq:'Role Name is a required field',
    catreq:'Category is a required field',
    newpassreq:'New password is a required field',
    yesdelete:'Yes, Delete!',
    nocancel:'No, Cancel!',
    unitreq:'Unit Number is a required field',
    pilgrimsreq:'Nationality is a required field',
    buildingreq:'Building Number is a required field',
    representreq:'Representative is a required field',
    clientreq:'Client is a required field',
    permissionreq:'Permissions is a required field',
    companyreq:'Company is a required field',
    typereq:'Type is a required field',
    percentagecontractor:'Percentages of completion of contractors',
    Contractor_ratios:'Contractor_ratios',
    masters:'Masters',
    industrytype:'Industry Type',
    inspectiontype:'Inspection Type',
    inspectionpropertytype:'Inspection Property Type',
    registeredproperty:'Registered Offices',
    addnewtype:'Add New Industry Type',
    name:'Name',
    arabic:'Arabic',
    english:'English',
    name_ar_req:'Name is required in arabic',
    name_en_req:'Name is required in english',
    addinspectiontype:'Add New Inspection Type',
    selectowner:'Select Property Owner',
    selectindustrytype:'Select Industry Type',
    ownerreq:'Please select owner',
    industryreq:'Please select industrytype',
    ownerreq_en:'Owner name is required in english',
    ownerreq_ar:'Owner name is required in arabic',
    owner:'Owner',
    selectproperty:'Select Inspection Property',
    list:'Office list',
    noofpeople:'Number Of People',
    inspectionreq:'Please select property type',
    noofpreq:'Field is required',
    active:'Active',
    archive:'Archive',
    action:'Action',
    selectinspectiontype:'Select inspectiom Type',
    selectinspectionproperty:'Select inspection property Type',
    selectregisteredproperty:'Select Registered property',
    editsurvey:'Update Survey',
    editcontractor:'Edit Contractor',
    passwordless:'Newpassword must be at least 6 characters',
    propertytype:'Property Type',
    editpropertytype:'Edit Property Type',
    addpropertytype:'Add Property Type',
    addregisteredproperty:'Add Registered Offices',
    selectpropertytype:'Select Property',
    passless:'Password must be at least 6 characters',
    emailmobile:'Email / Phone is required',
    emailphoneinvalid:'Email / Phone is invalid',
    addfields:'Add Fields',
    pleasetry:'Password Not Update! Please Try after Some time',
    yesarchive:'Yes Archive',
    representative:'Representative',
    reqselectproperty:'Please select property',
    permitnoreq:'Permit number is a required field',
    owner_req:'owner is a required field',
    offices:'Offices',
    buildingname:'Building Name',
    buildingnamereq:'Building Name is a required field',
    licenseno:'License Number',
    newpassword:'New Password',
    enterpassword:'Please Enter new password',
    registeredproperties:'Registered Properties',
    addrolegroup:'Add User Role Group',
    addinspectionpropertytype:'Add New Inspection Property Type',
    addusergroup:'Add User Group ',
    adduserrole:'Add New User Role',


  }

  export default en;