const es = {
    dashboard: "Tablero",
    layoutBuilder: "Constructor de maquetación",
    craft: "Elaborado",
    pages: "Paginas",
    profile: "Perfil",
    profileOverview: "Descripción general",
    projects: "Proyectos",
    campaigns: "Campañas",
    documents: "Documentos",
    connections: "Conexiones",
    wizards: "Magos",
    horizontal: "Horizontal",
    vertical: "Vertical",
    account: "Cuenta",
    accountOverview: "Descripción general",
    settings: "Ajustes",
    authentication: "Autenticación",
    basicFlow: "Flujo básico",
    signIn: "Registrarse",
    signUp: "Inscribirse",
    passwordReset: "Restablecimiento de contraseña",
    multiStepSignUp: "Regístrese Multi-Pasos",
    error404: "Error 404",
    error500: "Error 500",
    apps: "Aplicaciones",
    chat: "Chat",
    privateChat: "Chat privado",
    groupChat: "Grupo de chat",
    drawerChat: "Chat del cajón",
    widgets: "Widgets",
    widgetsLists: "Liza",
    widgetsStatistics: "Estadísticas",
    widgetsCharts: "Gráficos",
    widgetsMixed: "Mezclada",
    widgetsTables: "Mesas",
    widgetsFeeds: "Alimenta",
    changelog: "Registro de cambios",
    docsAndComponents: "Documentos & Componentes",
    megaMenu: "Mega menú",
    exampleLink: "Enlace de ejemplo",
    modals: "Modales",
    general: "General",
    inviteFriends: "Invitar A Amigos",
    viewUsers: "Ver Usuarios",
    upgradePlan: "Plan De Actualización",
    shareAndEarn: "Compartir Y Ganar",
    forms: "Formas",
    newTarget: "Nuevo Objetivo",
    newCard: "Nueva Tarjeta",
    newAddress: "Nueva Direccion",
    createAPIKey: "Crea Clave De Api",
    twoFactorAuth: "Dos Factores",
    createApp: "Crear Aplicacion",
    createAccount: "Crear Una Cuenta",
    activity: "Actividad",
    documentation: "Documentación",
    components: "Componentes",
    resources: "Recursos",
    customers: "Clientes",
    gettingStarted: "Empezando",
    customersListing: "Listado De Clientes",
    customerDetails: "Detalles De Los Clientes",
    calendarApp: "Calendario",
    subscriptions: "Suscripciones",
    getStarted: "Empezando",
    subscriptionList: "Lista De Suscripción",
    addSubscription: "Añadir Suscripción",
    viewSubscription: "Suscripción",
    Generalpercentagesem:"Porcentajes generales para emergencias",
    Generalpercentageshr:"Ratios generales de recursos humanos",
    addcontractor:'Agregar contratista',
    listofunits:'Lista de módulos',
    addunitypes:'Adición de tipos de unidades',
    newunit:'Registrar una nueva unidad',
    listofusers:'Lista de usuarios',
    adduscores:'Agregar puntajes de usuario',
    category:'naturaleza del negocio',
    addnewuser:'Agregar un nuevo usuario',
    Reports:'Informes',
    performanceem:'Informe de desempeño del personal de emergencia',
    performancehr:"Informe de desempeño de los empleados de recursos humanos",
    humanresource:"informe de recursos humanos",
    emergency_report:"informe de emergencia",
    notcompletedtaskem:"Misiones de emergencia denegadas",
    notcompletedtaskhr:"Tareas de recursos humanos rechazadas",
    pendingtaskem:"Misiones de emergencia pendientes",
    pendingtaskhr:"Tareas pendientes de recursos humanos",
    completedtaskem: "Tareas de emergencia completadas",
    completedtaskhr:"Tareas de recursos humanos completadas",
    surveylistforreport:"Informes de plantilla",
    units_status_em:"Informe de tasa de finalización de emergencia",
    units_status_hr: "Informe de porcentajes de cumplimiento de recursos humanos",
    Applications:"Aplicaciones",
    todolist:"Lista de quehaceres",
    surveylist:"Crear una evaluación",
    survey:"Crear formularios",
    generalratios:'Ratios generales de recursos humanos',
    contractorlist:'Lista de contratistas:',
    listunits:'Lista de unidades:',
    listunittypes:'Lista de tipos de unidades:',
    unitregistrationform:'formulario de registro de unidad',
    userpermission:'Permisos de usuario',
    gradelist:'Lista de calificaciones de usuarios:',
    categorylist:'Lista de categoría',
    userregistrations:'Registro de usuario:',
    reportstaffem:'Informe de desempeño del personal de emergencia:',
    reportstaffhr:'Informe de desempeño del personal de recursos humanos:',
    hrreport:'informe de recursos humanos',
    emreport:'informe de emergencia',
    rejectassign:'Asignación rechazada',
    pendingtask:'Tareas pendientes',
    completedtask:'Tareas Completadas',
    passingpercentage:'Porcentajes de aprobación:',
    surveyt:'Evaluación',
    home:'Hogar',
    default_em:'por defecto',
    default:'Por defecto',
    contractor:'Contratista',
    unitsupdate:'Actualizar unidades',
    Unitestypes:'tipos de unidades',
    Units:'Unidades',
    usersupdate:'actualizar usuarios',
    roles:'papeles',
    natureb:'Categoría',
    register:'Registro',
    performance_em:'Rendimiento em',
    performance_hr:'Hora de rendimiento',
    human_resource:'Recursos humanos',
    EditList:'Lista de edición',
    totalrating:'Calificaciones totales',
    emergencytask:'Tareas de emergencia',
    hrtasks:'tareas de recursos humanos',
    holystage:'Etapa de sentimientos sagrados',
    noofflight:'El número de vuelos completados.',
    noofpilgrims:'El número de peregrinos',
    totallabor:'Mano de obra total ahorrada',
    averagetime:'Tiempo promedio para completar',
    averageno:'El número medio de trabajadores para el viaje.',
    departurestage:'etapa de salida',
    newcontractor:'Agregar un nuevo contratista',
    serialno:'número de serie',
    contractorname:'nombre del contratista',
    buildingno:'Número de edificio',
    customername:'Nombre del cliente',
    unitno:'unidad numérica',
    typeunit:'tipo de unidad',
    events:'Eventos',
    details:'Detalles',
    placecontractor:'Por favor ingrese el nombre del contratista aquí',
    cancel:'cancelación',
    save:'ahorrar',
    pleasewait:'Espere por favor...',
    reqcon:'se requiere el nombre del contratista',
    addunittype:'Agregar un nuevo tipo de unidad',
    placeunittype:'Por favor ingrese el tipo de unidad aquí',
    requnittype:'se requiere el tipo de unidad',
    reqcat:'la categoria es requerida',
    addnewunit:'Agregar una nueva unidad',
    deparmentname:'Nombre de Departamento',
    reqscore:'se requiere puntuación',
    userscore:'puntuación de usuario',
    placescore:'Ingrese la puntuación del usuario aquí',
    addnewscore:'Añadir una nueva puntuación de usuario',
    addnewsurvey:'Agregar una nueva encuesta',
    title:'Título',
    cat:'categoría',
    detail:'Detalles',
    reqtitle:'Se requiere título',
    detailreq:"Se requiere detalle",
    selectcategory:"Por favor seleccione categoría",
    savedsuccess:'Guardado exitosamente',
    hajj:'Unidades Ejecutivas Hajj Servicios Hajj No',
    nationality:'Nacionalidad',
    buidling_owner:'El nombre del dueño del edificio.',
    permitno:'numero de permiso',
    selectcontractor:'Elige al contratista',
    typeunits:'Tipos de unidades',
    uploadfile:'subir archivo',
    firstname:'Nombre de pila',
    lastname:'apellido',
    mobile:'Número de teléfono móvil',
    e_mail:'Correo electrónico',
    function:'Función',
    validity:'Validez',
    powers:'potestades',
    additions:'suma',
    delete:'borrar',
    unitname:'Nombre de la unidad',
    process:'Procesos',
    areyousure:'está seguro ?',
    notretrivedata:'¡No podrá volver a recuperar datos!',
    deletesuccess:'Borrado exitosamente',
    cancelerror:'"Cancelar", "Datos no eliminados", "Error"',
    phone:'número de telefono',
    password:'contraseña',
    selectdegree:'Elige el grado',
    choosecategory:'Elegir la categoría',
    registration:'registro',
    discard:'Desechar',
    export:'Exportar',
    rejectemtask:'Tareas de emergencia rechazadas:',
    rejecthrtask:'Tareas rechazadas relacionadas con los recursos humanos:',
    signout:'Desconectar',
    signin:'Iniciar sesión',
    continue:'continuar',
    successloggedin:'¡Has iniciado sesión correctamente!',
    okgotit:'¡Ok lo tengo!',
    tryagain:'¡Intentar otra vez!',
    thedate:'la fecha',
    thedetails:'los detalles',
    themission:'la misión',
    thecondition:'la condición',
    unitadministrator:'Administrador de unidad',
    pendingemtask:'Tareas pendientes de emergencia:',
    pendinghrtask:'Tareas pendientes de RRHH:',
    completedemtask:'Tareas completadas de emergencia:',
    completedhrtask:'Tareas de recursos humanos completadas:',
    theuser:'el usuario',
    buildingn:'Número de edificio',
    executiveunit:'unidad ejecutiva',
    theevent:'el evento',
    printing:'impresión',
    amendment:'Enmienda',
    print:'imprimir',
    unit:'Unidad',
    thequestion:'la pregunta',
    theanswers:'las respuestas',
    attachments:'archivos adjuntos',
    comments:'comentarios',
    taskimage:'imagen de la tarea',
    tasknotes:'notas de tareas',
    taskstatus:'estado de la tarea',
    usertask:'tarea de usuario',
    sample:'Muestra',
    formdetails:'Detalles del formulario',
    successrate:'la tasa de éxito',
    mistakepercentage:'porcentaje de error',
    searchbymodelname:'Buscar por nombre de modelo',
    searchbyunitno:'Buscar por número de unidad',
    searchbyinsname:'Buscar por nombre de inspector',
    search:'Buscar',
    question:'Pregunta',
    status:'Estado',
    date:'Fecha',
    missiondetails:'Detalles de la misión',
    taskname:'Nombre de la tarea',
    attachfile:'Adjuntar un archivo',
    tobesure:'para estar seguro',
    completed:'terminado',
    suspended:'suspendido',
    notdone:'no hecho',
    chooseunit:'Elige la unidad',
    employeename:'Nombre de empleado',
    undertaker:'enterrador',
    assignto:'asignar a',
    addnew:'Agregar nuevo',
    summary:'Resumen',
    edit:'Editar',
    addquestions:'Agregar preguntas',
    text:'texto',
    choosemultiple:'Elija entre múltiples',
    multiplechoice:'Opción multiple',
    answertype:'tipo de respuesta',
    addanswer:'Agregar una respuesta',
    changepassword:'cambiar la contraseña',
    light:'Ligero',
    dark:'oscura',
    system:'Sistema',
    quicklink:'enlaces rápidos',
    generalproportion:'Las proporciones generales son contingentes.',
    generalpresources:'Recursos de proporciones generales',
    achievementratios:'Proporciones de logro',
    generalcompletion:'Porcentajes de finalización de recursos',
    accomplishmentcontractor:'Realización de contratistas',
    notifications:'Notificaciones',
    viewall:'Ver todo',
    About:'Acerca de',
    Support:'Apoyo',
    Purchase:'Compra',
    permission:'permiso',
    passwordsave:'Contraseña cambiada con éxito',
    newpass:'Nueva contraseña',
    emailreq:'El correo electrónico es un campo obligatorio',
    passreq:'La contraseña es un campo requerido',
    terms:"Términos",
    plans:'planes',
    contactus:'Contacta con nosotros'
  }
  export default es;